"""Add default euthanasia fields to ExperimentalGroup

Revision ID: 11bd15b7bc61
Revises: edbe4f506854
Create Date: 2026-01-16 18:08:26.130549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bd15b7bc61'
down_revision = 'edbe4f506854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experimental_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_euthanasia_reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_severity', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experimental_group', schema=None) as batch_op:
        batch_op.drop_column('default_severity')
        batch_op.drop_column('default_euthanasia_reason')

    # ### end Alembic commands ###
