"""Initial_Baseline

Revision ID: 500214ecd7ea
Revises: 
Create Date: 2026-01-11 17:53:19.502677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500214ecd7ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('anticoagulant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('derived_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derived_sample_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_type', sa.Enum('BLOOD', 'URINE', 'BIOLOGICAL_TISSUE', 'OTHER', name='sampletype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_contact_email'), ['contact_email'], unique=False)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_resource'), ['resource'], unique=False)

    op.create_table('protocol_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('NONE', 'LIGHT', 'MODERATE', 'SEVERE', name='severity'), nullable=False),
    sa.Column('external_skill_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staining',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tissue_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('ckan_url', sa.String(length=255), nullable=True),
    sa.Column('ckan_api_key', sa.String(length=255), nullable=True),
    sa.Column('calendar_token', sa.String(length=64), nullable=True),
    sa.Column('team_calendar_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_token', name='uq_user_calendar_token'),
    sa.UniqueConstraint('team_calendar_token', name='uq_user_team_calendar_token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('analyte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.Enum('FLOAT', 'INT', 'TEXT', 'CATEGORY', 'DATE', name='analytedatatype'), nullable=False),
    sa.Column('allowed_values', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('is_metadata', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('analyte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyte_is_mandatory'), ['is_mandatory'], unique=False)

    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controlled_molecule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('regulation_category', sa.Enum('STUPEFIANT', 'ASSIMILE_STUPEFIANT', 'MOLECULE_CONTROLEE', 'AUTRE', name='regulationcategory'), nullable=False),
    sa.Column('storage_location', sa.String(length=500), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('cas_number', sa.String(length=50), nullable=True),
    sa.Column('internal_reference', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('requires_secure_prescription', sa.Boolean(), nullable=False),
    sa.Column('max_prescription_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('controlled_molecule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controlled_molecule_internal_reference'), ['internal_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_controlled_molecule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_controlled_molecule_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_controlled_molecule_regulation_category'), ['regulation_category'], unique=False)

    op.create_table('ethical_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('apafis_reference', sa.String(length=50), nullable=True),
    sa.Column('apafis_version', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('sex_justification', sa.Text(), nullable=True),
    sa.Column('number_of_animals', sa.Integer(), nullable=False),
    sa.Column('euthanasia_method', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('overall_severity', sa.Enum('NONE', 'LIGHT', 'MODERATE', 'SEVERE', name='severity'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('ethical_approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ethical_approval_apafis_reference'), ['apafis_reference'], unique=False)

    op.create_table('housing_condition_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('FLOAT', 'INT', 'TEXT', 'CATEGORY', 'DATE', name='analytedatatype'), nullable=False),
    sa.Column('allowed_values', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('housing_condition_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('ckan_upload_date', sa.DateTime(), nullable=True),
    sa.Column('ckan_dataset_id', sa.String(length=255), nullable=True),
    sa.Column('ckan_organization_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='_project_team_name_uc')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_team_id'), ['team_id'], unique=False)

    op.create_table('protocol_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'team_id', name='uq_role_name_team')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_team_id'), ['team_id'], unique=False)

    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.String(length=100), nullable=True),
    sa.Column('location_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='_storage_team_name_uc')
    )
    op.create_table('team_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='_user_team_uc')
    )
    op.create_table('animal_model_analyte_association',
    sa.Column('animal_model_id', sa.Integer(), nullable=False),
    sa.Column('analyte_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analyte_id'], ['analyte.id'], ),
    sa.ForeignKeyConstraint(['animal_model_id'], ['animal_model.id'], ),
    sa.PrimaryKeyConstraint('animal_model_id', 'analyte_id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('ckan_upload_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ethical_approval_procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethical_approval_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'LIGHT', 'MODERATE', 'SEVERE', name='severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pain_management', sa.Text(), nullable=True),
    sa.Column('is_euthanasia_endpoint', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ethical_approval_id'], ['ethical_approval.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ethical_approval_team_share',
    sa.Column('ethical_approval_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ethical_approval_id'], ['ethical_approval.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ethical_approval_id', 'team_id')
    )
    op.create_table('housing_set_item_association',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['housing_condition_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['housing_condition_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'item_id')
    )
    op.create_table('project_ethical_approval_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ethical_approval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ethical_approval_id'], ['ethical_approval.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'ethical_approval_id')
    )
    op.create_table('project_partner_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'partner_id')
    )
    op.create_table('project_team_share',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('can_view_project', sa.Boolean(), nullable=False),
    sa.Column('can_view_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_view_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_view_samples', sa.Boolean(), nullable=False),
    sa.Column('can_create_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_edit_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_delete_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_create_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_edit_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_delete_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_view_unblinded_data', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'team_id')
    )
    op.create_table('project_user_share',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=True),
    sa.Column('can_view_project', sa.Boolean(), nullable=False),
    sa.Column('can_view_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_view_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_view_samples', sa.Boolean(), nullable=False),
    sa.Column('can_create_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_edit_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_delete_exp_groups', sa.Boolean(), nullable=False),
    sa.Column('can_create_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_edit_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_delete_datatables', sa.Boolean(), nullable=False),
    sa.Column('can_view_unblinded_data', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('protocol_analyte_association',
    sa.Column('protocol_model_id', sa.Integer(), nullable=False),
    sa.Column('analyte_id', sa.Integer(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('is_metadata', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analyte_id'], ['analyte.id'], ),
    sa.ForeignKeyConstraint(['protocol_model_id'], ['protocol_model.id'], ),
    sa.PrimaryKeyConstraint('protocol_model_id', 'analyte_id')
    )
    op.create_table('protocol_molecule_association',
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('molecule_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_volume', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['molecule_id'], ['controlled_molecule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('protocol_id', 'molecule_id')
    )
    op.create_table('reference_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('analyte_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('animal_model_id', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('included_animals', sa.JSON(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_globally_shared', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analyte_id'], ['analyte.id'], ),
    sa.ForeignKeyConstraint(['animal_model_id'], ['animal_model.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol_model.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='_reference_range_team_name_uc')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('storage_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_team_role_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id', 'role_id')
    )
    op.create_table('workplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('animal_model_id', sa.Integer(), nullable=True),
    sa.Column('planned_animal_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'RUNNING', 'COMPLETED', 'ARCHIVED', name='workplanstatus'), nullable=False),
    sa.Column('study_start_date', sa.Date(), nullable=True),
    sa.Column('expected_dob', sa.Date(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_model_id'], ['animal_model.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['workplan_version.id'], name='fk_workplan_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ckan_resource_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_task_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ckan_resource_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_task_id'], ['ckan_upload_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experimental_group',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ethical_approval_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('animal_data', sa.JSON(), nullable=True),
    sa.Column('randomization_details', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_from_workplan_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_from_workplan_id'], ['workplan.id'], ),
    sa.ForeignKeyConstraint(['ethical_approval_id'], ['ethical_approval.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['animal_model.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='_project_group_name_uc')
    )
    with op.batch_alter_table('experimental_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimental_group_ethical_approval_id'), ['ethical_approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_group_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_group_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_group_project_id'), ['project_id'], unique=False)

    op.create_table('reference_range_team_share',
    sa.Column('reference_range_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_range_id'], ['reference_range.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reference_range_id', 'team_id')
    )
    op.create_table('workplan_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workplan_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'SKIPPED', name='workplaneventstatus'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol_model.id'], ),
    sa.ForeignKeyConstraint(['workplan_id'], ['workplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workplan_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workplan_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('change_comment', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workplan_id'], ['workplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('workplan_event_id', sa.Integer(), nullable=True),
    sa.Column('housing_condition_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['experimental_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['housing_condition_set_id'], ['housing_condition_set.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol_model.id'], ),
    sa.ForeignKeyConstraint(['workplan_event_id'], ['workplan_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_table_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_table_group_id'), ['group_id'], unique=False)

    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(length=100), nullable=True),
    sa.Column('parent_sample_id', sa.Integer(), nullable=True),
    sa.Column('experimental_group_id', sa.String(length=40), nullable=False),
    sa.Column('animal_index_in_group', sa.Integer(), nullable=False),
    sa.Column('sample_type', sa.Enum('BLOOD', 'URINE', 'BIOLOGICAL_TISSUE', 'OTHER', name='sampletype'), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('TO_BE_COLLECTED', 'STORED', 'SHIPPED', 'DESTROYED', 'USED_FOR_DERIVATION', name='samplestatus'), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=True),
    sa.Column('destruction_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('derived_type_id', sa.Integer(), nullable=True),
    sa.Column('staining_id', sa.Integer(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('anticoagulant_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('volume_unit', sa.String(length=20), nullable=True),
    sa.Column('organ_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['anticoagulant_id'], ['anticoagulant.id'], ),
    sa.ForeignKeyConstraint(['derived_type_id'], ['derived_sample_type.id'], ),
    sa.ForeignKeyConstraint(['experimental_group_id'], ['experimental_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organ_id'], ['organ.id'], ),
    sa.ForeignKeyConstraint(['parent_sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['staining_id'], ['staining.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_display_id'), ['display_id'], unique=False)

    op.create_table('user_my_page_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['experimental_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('data_table_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_table_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_table_id'], ['data_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('data_table_molecule_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_table_id', sa.Integer(), nullable=False),
    sa.Column('molecule_id', sa.Integer(), nullable=False),
    sa.Column('volume_used', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('animal_ids', sa.JSON(), nullable=True),
    sa.Column('number_of_animals', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('administration_route', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_table_id'], ['data_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['molecule_id'], ['controlled_molecule.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_table_molecule_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_table_molecule_usage_data_table_id'), ['data_table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_table_molecule_usage_molecule_id'), ['molecule_id'], unique=False)

    op.create_table('experiment_data_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_table_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('row_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['data_table_id'], ['data_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_table_id', 'row_index', name='_data_table_row_uc')
    )
    op.create_table('sample_conditions',
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['tissue_condition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sample_id', 'condition_id')
    )
    op.create_table('user_my_page_datatables',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datatable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['datatable_id'], ['data_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'datatable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_my_page_datatables')
    op.drop_table('sample_conditions')
    op.drop_table('experiment_data_row')
    with op.batch_alter_table('data_table_molecule_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_table_molecule_usage_molecule_id'))
        batch_op.drop_index(batch_op.f('ix_data_table_molecule_usage_data_table_id'))

    op.drop_table('data_table_molecule_usage')
    op.drop_table('data_table_file')
    op.drop_table('user_my_page_groups')
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_display_id'))

    op.drop_table('sample')
    with op.batch_alter_table('data_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_table_group_id'))
        batch_op.drop_index(batch_op.f('ix_data_table_date'))

    op.drop_table('data_table')
    op.drop_table('workplan_version')
    op.drop_table('workplan_event')
    op.drop_table('reference_range_team_share')
    with op.batch_alter_table('experimental_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimental_group_project_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_group_name'))
        batch_op.drop_index(batch_op.f('ix_experimental_group_is_archived'))
        batch_op.drop_index(batch_op.f('ix_experimental_group_ethical_approval_id'))

    op.drop_table('experimental_group')
    op.drop_table('ckan_resource_task')
    op.drop_table('workplan')
    op.drop_table('user_team_role_link')
    op.drop_table('storage_location')
    op.drop_table('role_permissions')
    op.drop_table('reference_range')
    op.drop_table('protocol_molecule_association')
    op.drop_table('protocol_analyte_association')
    op.drop_table('project_user_share')
    op.drop_table('project_team_share')
    op.drop_table('project_partner_association')
    op.drop_table('project_ethical_approval_association')
    op.drop_table('housing_set_item_association')
    op.drop_table('ethical_approval_team_share')
    op.drop_table('ethical_approval_procedure')
    op.drop_table('ckan_upload_task')
    op.drop_table('attachment')
    op.drop_table('animal_model_analyte_association')
    op.drop_table('team_membership')
    op.drop_table('storage')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_team_id'))

    op.drop_table('role')
    op.drop_table('protocol_attachment')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_team_id'))
        batch_op.drop_index(batch_op.f('ix_project_slug'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_is_archived'))

    op.drop_table('project')
    op.drop_table('housing_condition_set')
    op.drop_table('housing_condition_item')
    with op.batch_alter_table('ethical_approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ethical_approval_apafis_reference'))

    op.drop_table('ethical_approval')
    with op.batch_alter_table('controlled_molecule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controlled_molecule_regulation_category'))
        batch_op.drop_index(batch_op.f('ix_controlled_molecule_name'))
        batch_op.drop_index(batch_op.f('ix_controlled_molecule_is_active'))
        batch_op.drop_index(batch_op.f('ix_controlled_molecule_internal_reference'))

    op.drop_table('controlled_molecule')
    op.drop_table('audit_log')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_token_hash'))

    op.drop_table('api_token')
    with op.batch_alter_table('analyte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyte_is_mandatory'))

    op.drop_table('analyte')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('tissue_condition')
    op.drop_table('team')
    op.drop_table('staining')
    op.drop_table('protocol_model')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_resource'))
        batch_op.drop_index(batch_op.f('ix_permission_action'))

    op.drop_table('permission')
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_contact_email'))

    op.drop_table('partner')
    op.drop_table('organ')
    op.drop_table('derived_sample_type')
    op.drop_table('derived_sample')
    op.drop_table('anticoagulant')
    op.drop_table('animal_model')
    # ### end Alembic commands ###
