"""Add Animal hybrid table

Revision ID: 8b56d2e75b54
Revises: 0d4b0b90ad21
Create Date: 2026-01-29 14:01:40.177839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b56d2e75b54'
down_revision = '0d4b0b90ad21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.Column('sex', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('measurements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['experimental_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_uid'), ['uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_uid'))
        batch_op.drop_index(batch_op.f('ix_animal_status'))
        batch_op.drop_index(batch_op.f('ix_animal_group_id'))

    op.drop_table('animal')
    # ### end Alembic commands ###
