"""Add index to Animal.date_of_birth

Revision ID: df0b4cbbb265
Revises: 8b56d2e75b54
Create Date: 2026-02-02 11:21:54.795788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'df0b4cbbb265'
down_revision = '8b56d2e75b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_date_of_birth'), ['date_of_birth'], unique=False)

    with op.batch_alter_table('experimental_group', schema=None) as batch_op:
        batch_op.drop_column('animal_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experimental_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_date_of_birth'))

    # ### end Alembic commands ###
