"""empty message

Revision ID: edbe4f506854
Revises: 500214ecd7ea
Create Date: 2026-01-15 13:55:03.155822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbe4f506854'
down_revision = '500214ecd7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('protocol_model_id', sa.Integer(), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('skip_rows', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.String(length=255), nullable=True),
    sa.Column('anchor_offset', sa.Integer(), nullable=False),
    sa.Column('row_interval', sa.Integer(), nullable=False),
    sa.Column('advanced_logic', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_model_id'], ['protocol_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix_hash', sa.String(length=128), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_api_token_prefix_hash'), ['prefix_hash'], unique=True)
        batch_op.drop_column('prefix')

    with op.batch_alter_table('protocol_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_import_wizard', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocol_model', schema=None) as batch_op:
        batch_op.drop_column('enable_import_wizard')

    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=8), nullable=False))
        batch_op.drop_index(batch_op.f('ix_api_token_prefix_hash'))
        batch_op.drop_column('prefix_hash')

    op.drop_table('import_template')
    # ### end Alembic commands ###
